### ISSUE TITLE
标题、导航

### ISSUE THREAD

**Issue by songjilong** [BNDong/Cnblogs-Theme-SimpleMemory#128]
# 给标题加上编号后，导航栏看的很不方便
![image](https://user-images.githubusercontent.com/47097549/78214815-b10ee700-74e8-11ea-8edb-5f22fb5ecd63.png)
----
建议添加一个**是否显示自带编号**的选项

**Comment by BNDong** [comment]
可以尝试增加 css

```css
.dev__fe, .dev__slash, .dev__ux {
    display: none !important;
}
b.dev__developer {
    left: 40px !important;
}
```
