### ISSUE TITLE
关于右侧滚动条

### ISSUE THREAD

**Issue by HeatDeathOfUniverse** [BNDong/Cnblogs-Theme-SimpleMemory#160]
这么好看的皮肤，右侧的滚动条过于显眼。能不能改成设置是否开启右侧滚动条？

**Comment by BNDong** [comment]
其实刚开始是不显示右侧滚动条的，但是很多人私信我希望显示出滚动条，所以就放开了！

如果想隐藏滚动条，在css中添加样式：

```css
body::-webkit-scrollbar {
    display:none
}
```
