### ISSUE TITLE
如何修改主页欢迎界面的字体

### ISSUE THREAD

**Issue by ylighgh** [BNDong/Cnblogs-Theme-SimpleMemory#163]
如何修改主页欢迎界面的字体，感觉有点花 不太能够看得清楚

https://ylighgh.github.io

**Comment by BNDong** [comment]
自行修改相关样式字体。
```css
.page-title {
    font-family: 'Playball',cursive;
}
.page-description {
    font-family: 'Long Cang',cursive;
}
.page-author {
    font-family:'Ubuntu Mono',monospace;
}
```
