### ISSUE TITLE
标题如何改颜色

### ISSUE THREAD

**Issue by zhaobo0564** [BNDong/Cnblogs-Theme-SimpleMemory#172]
![图片](https://user-images.githubusercontent.com/49364302/85594951-fd4a6d00-b67a-11ea-86c1-5ec567f66675.png)
标题颜色怎么改？
求助

**Comment by BNDong** [comment]
增加 css 样式：
```css
#homeTopTitle {
    color: red;  /*  你的颜色值 */
}
```
