### ISSUE TITLE
文章目录局限性

### ISSUE THREAD

**Issue by liu844869663** [BNDong/Cnblogs-Theme-SimpleMemory#205]
1. 如何让目录默认全部展开？
2. 能否支持更多级别的标题？

**Comment by liu844869663** [comment]
有讨论的群吗？

**Comment by BNDong** [comment]
### 如何让目录默认全部展开？
现在目录子级标题的显示和隐藏是通过页面上下滚动事件监听来控制的，目前没有相关配置来控制此功能。
如果，你需要全部展开，目前可以通过修改css来实现：

```css
#sideCatalog li.h2Offset {
    display: block !important;
}
```
### 能否支持更多级别的标题？

目前只支持到二级目录。不想往下兼容，主要也是考虑两个方面：
1）标题的使用不规范；有的用户使用小标题，单纯的只是想加粗文字，并不是为了标题而设置标题！
2）更多的层级计算起来比较复杂；例如，文章目录为h2 h1 h2 h3 h1 h3 h4 h1 h2 h1 h2，如果一级标题和子级标题出现断层，目录应该怎么显示也是个问题！！

### 有讨论的群吗？

没有
