### ISSUE TITLE
优化建议：增加markdown 代码块折叠开关

### ISSUE THREAD

**Issue by gaotianhao1994** [BNDong/Cnblogs-Theme-SimpleMemory#276]
如题。
可以防止代码块影响文章阅读，提高阅读体验

**Comment by TRSWNCA** [comment]
代码折叠可以通过 `<details>` 标签来用

例如，
```
<details>
<summary> 代码 </summary>

/* 空一行然后插入代码块然后空一行 */

</details>
```

<details>
<summary> 代码 </summary>

```cpp
printf("Hello World");
```

</details>

**Comment by TRSWNCA** [comment]
你可以在我的这篇博文看到我对样式的修改 https://www.cnblogs.com/trswnca/p/bzoj1036.html

具体是添加MDesign图标

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/material-icons@0.2.3/iconfont/material-icons.min.css">
```

添加样式
```css
details {
    margin: 1.5rem 0;
    padding: .5rem 1rem;
    background: #448aff1a;
    border: 1px solid #1B86F9;
    border-radius: 3px;
}

summary {
    display: block;
    outline: none;
    cursor: pointer;
}

details>summary:before {
    font-family: Material Icons!important;
    font-style: normal!important;
    left: .6rem;
    color: #448aff;
    font-size: 1.5rem;
    content: "\e3c9";
}

details>summary:after {
    font-family: Material Icons!important;
    font-style: normal!important;
    top: .4rem;
    float: right;
    color: rgba(0,0,0,.26);
    font-size: 1.5rem;
    content: "\e313";
}
```
