### ISSUE TITLE
文章图片不居中了

### ISSUE THREAD

**Issue by Scholar-City** [BNDong/Cnblogs-Theme-SimpleMemory#315]
为啥用了之后，文章图片不居中了

**Comment by Scholar-City** [comment]
用的 v2.1.0 css 跟 <script src="https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@2.1.0/dist/simpleMemory.js" defer></script> js

博客地址：https://www.cnblogs.com/miruier/p/15733624.html

**Comment by Jayant-Tang** [comment]
我研究了一晚上搞定了
CSS加一行：
```CSS
a[data-fancybox="gallery"] {
  display: block; /* 设置为块级元素 */
  margin: 0 auto; /* 左右居中 */

  text-align: center; /* 使子元素（也就是图片）居中 */
}
```
