### ISSUE TITLE
sidebar-search

### ISSUE THREAD

**Issue by yuitoTDF** [BNDong/Cnblogs-Theme-SimpleMemory#372]
侧边栏搜索问题:
1. 图标显示错位
2. 无输入框
![错位示例](https://user-images.githubusercontent.com/109447387/215669306-3293c705-65c5-4d34-a673-83e1f55b4436.png)
目前暂时解决方法:css不显示sidebar-search：
```css
div.sidebar-search {
    display: none!important;
}
```

More Information:
`ErrVer`:`2.1.2`
<details>
<summary>JS配置</summary>

```html
<script type="text/javascript">
    window.cnblogsConfig = {
      info: {
        startDate: '2022-11-23', // 入园时间，年-月-日。入园时间查看方法：鼠标停留园龄时间上，会显示入园时间
        avatar: 'https://pic.cnblogs.com/avatar/3044840/20230103180842.png',
      },
      sidebar: {
        titleMsg: 'The sooner you start to code, the longer the program will take. —— Roy Carlson',
      },
      rtMenu: {
        reward: {
          wechatpay: 'https://pic.cnblogs.com/avatar/3044840/20230103180842.png'
        },
      },
      switchDayNight: {
        auto: {
            enable: true
        }
      },
      code: {
        options: {
          macStyle: true,
          maxHeight: '50%',
        },
      },
      banner: {
        home: {
            title: [
                'The sooner you start to code, the longer the program will take. —— Roy Carlson',
                'Don\'t debug standing up. It cuts your patience in half, and you need all you can muster. —— Dave Storer',
                'Testing can show the presence of bugs, but not their absence. —— Edsger W. Dijkstra',
                'Don\'t worry if it doesn\'t work right.If everything did,you\'d be out of a job. —— Mosher\'s Law of Software Engineering',
                'Whenever possible, steal code. —— Tom Duff',
            ],
        },
      },
    }
</script>
<script src="https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v2.1.2/dist/simpleMemory.js" defer></script>
```
</details>
<details>
<summary>CSS代码</summary>

```css
[Code in <https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/dist/simpleMemory.css>]
img {
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 5px;
    width: 150px;
}
div#blog_post_info_block,
div.postDesc,
div#cnblogs_ch,
div.under-post-card,
div[id^="under_post_card"] {
    display: none;
}
div.sidebar-userinfo {
    padding-left: 0px!important;
    margin-top: 0px!important;
}
div.sidebar-search {
    display: none!important;
}
```
</details>
