### ISSUE TITLE
你最新的主题：Cnblogs-Theme-SimpleMemory-Test代码复制、语法高亮只对html有效吗？

### ISSUE THREAD

**Issue by juejian** [BNDong/Cnblogs-Theme-SimpleMemory#41]
我测试了下，目前对markdown无效。

最近一直麻烦你解答问题，太感谢了。

**Comment by BNDong** [comment]
markdown无效，博客园本身对markdown代码就是无效的

> 尽量不要用 Cnblogs-Theme-SimpleMemory-Test 库，这是我调试测试的库！

**Comment by juejian** [comment]
ok,

经测试发现：`highlightjs` 插件代码高亮主题， **只有** `hljs backgroud,color` **属性未生效**，被博客园公共的css(非模板css样式覆盖了)，所以未生效，其他正常。

`https://www.cnblogs.com/css/blog-common.min.css` 中定义

```css
.cnblogs-markdown .hljs, .cnblogs-post-body .hljs {
    display: block;
    overflow-x: auto;
    padding: .5em;
    background: #fff;
    color: #000;
}
```

highlightjs插件对应的hljs代码主题定义

```css
.hljs {
    display: block;
    overflow-x: auto;
    background: #2d2d2d;
    color: #cccccc;
    padding: .5em;
}
```

**解决办法：** 将自己选择的'highlightjs' 对应主题的backgroud,color属性复制下，在base.css中按照如下定义：

代码主题对应的样式文件url: `https://cdn.bootcss.com/highlight.js/9.15.9/styles/' + hltheme + '.min.css'`

```css
.cnblogs-markdown .hljs, .cnblogs-post-body .hljs {
    background: xxx;
    color: xxx;
}
```
