### ISSUE TITLE
博客园VIP图标位置和昵称有重合

### ISSUE THREAD

**Issue by yinghualuowu** [BNDong/Cnblogs-Theme-SimpleMemory#441]
![image](https://github.com/user-attachments/assets/8152d4ff-4bf4-403a-a5ef-8c5250c967b0)

**Comment by wangyang0210** [comment]
后续会提交代码修复，可以先在博客园设置，自定义css中使用以下css代码临时兼容；
```css
img.sidebar-vip-logo {
    height: 11px;
    left: 89px !important;
    position: absolute;
    top: 7px !important;
    vertical-align: middle;
    width: 11px;
}
```
