### ISSUE TITLE
关于代码美化

### ISSUE THREAD

**Issue by alessandrocyc** [BNDong/Cnblogs-Theme-SimpleMemory#6]
感觉如果博主要做代码美化的话调css会很累，附上我的用google-code-prettify渲染的代码美化

在css里，**代码样式**部分换成
(其中那一整段的样式可以去google-code-prettify官方找想要的样式覆盖）
```css
/* ==========================================================================
   代码样式
   ========================================================================== */
pre {
    /*控制代码不换行*/
    white-space: pre;
    word-wrap: normal;
    font-family: Consolas,Monaco, monospace,Ubuntu Mono,"Source Code Pro",Courier New!important;
}

.cnblogs-markdown .hljs {
    display: block;
    overflow-x: auto;
    white-space: pre;
    font-family: Consolas,Monaco, monospace,Ubuntu Mono,"Source Code Pro",Courier New!important;
    word-break: normal;
    border: none!important;
    padding: .8em!important;
    font-size: 0.85em!important;
}

.pln{color:#4d4d4c}ol.linenums{margin-top:0;margin-bottom:0;color:#8e908c}li.L0,li.L1,li.L2,li.L3,li.L4,li.L5,li.L6,li.L7,li.L8,li.L9{padding-left:1em;background-color:#fff;list-style-type:decimal!important;}@media screen{.str{color:#718c00}.kwd{color:#8959a8}.com{color:#8e908c}.typ{color:#4271ae}.lit{color:#f5871f}.pun{color:#4d4d4c}.opn{color:#4d4d4c}.clo{color:#4d4d4c}.tag{color:#c82829}.atn{color:#f5871f}.atv{color:#3e999f}.dec{color:#f5871f}.var{color:#c82829}.fun{color:#4271ae}}

/*下面是我设置背景色，字体大小和字体*/
.cnblogs-markdown code{
background:#fff!important;
}
.cnblogs_code,.cnblogs_code span,.cnblogs-markdown .hljs{
    font-size:18px!important;
}

.syntaxhighlighter a, .syntaxhighlighter div, .syntaxhighlighter code, .syntaxhighlighter table, .syntaxhighlighter table td, .syntaxhighlighter table tr, .syntaxhighlighter table tbody, .syntaxhighlighter table thead, .syntaxhighlighter table caption, .syntaxhighlighter textarea {
    font-size: 18px!important;
}

.cnblogs_code, .cnblogs_code span, .cnblogs-markdown .hljs{
font-family:consolas, "Source Code Pro", monaco, monospace !important;
}
```

然后在**页脚html**中加上
```cpp
<!-- Code -->
<script src="https://files.cnblogs.com/files/flipped/prettify.js"></script>
<script type="text/javascript">
(function() {
     $("pre").addClass("prettyprint");
     prettyPrint();
})();
</script>
```
